apiVersion: "ui.kyma-project.io/v1alpha1"
kind: ClusterMicroFrontend
metadata:
  name: addonsmicrofrontend
  labels:
    app:  addonsmicrofrontend
spec:
  displayName: "Add-Ons Config"
  version: v1
  category: Integration
  placement: cluster
  viewBaseUrl: 'https://add-ons.kyma.local'
  navigationNodes:
    - label: "Add-Ons Config"
      navigationPath: add-ons-config
      viewUrl: ''
      order: 4